### ISSUE TITLE
Icon in menu are cut off 

### ISSUE THREAD

**Issue by KarkanAlzwayed** [MartinF99/PlastikStyle#8] opened 2023-08-16 12:06 UTC
When I right-click on dolphin, the action menu icons are cut off. They are fine on the desktop, but not on dolphin. Not sure if this is something related to plastik, but it only happens on it. Keep in mind that I have a 4k screen, and I'm also running the `export PLASMA_USE_QT_SCALING=1` in `/etc/environment` if that matters. Since I use Xorg and the menus would have tiny icons without adding that line.

![Screenshot_20230815_142418](https://github.com/MartinF99/PlastikStyle/assets/49320606/8d4bb299-5ac7-458d-a6ce-5d2736d9b9af)

**Comment by MartinF99** [comment] 2023-08-16 12:18
Yes it's a bug I know about and is rooted in the lack of scaling support in Plastik. I'm already working on that 
duplicate of #6

**Closed by MartinF99** 2023-08-16 12:18 UTC
Labels: duplicate

**Comment by KarkanAlzwayed** [comment] 2023-08-16 12:24
Oh my bad then. I should have checked out the issues.

**Comment by MartinF99** [comment] 2023-09-26 18:41
this should be fixed now
